# Skims Configuration File for WackoPicko Security Scan
# Based on working configuration from Fluid Attacks community

# Namespace for organizing results
namespace: "wackopicko-security-scan"

# Working directory
working_dir: "."

# Output settings
output:
  file_path: "wackopicko-security-results.csv"
  format: "CSV"

# Checks to enable
checks:
  F001: true  # SQL Injection
  F004: true  # Cross-Site Scripting (XSS)
  F008: true  # Path Traversal
  F015: true  # Weak Random
  F016: true  # Insecure Random
  F021: true  # Path Injection
  F024: true  # HTTP Response Splitting
  F034: true  # Unvalidated Redirect
  F037: true  # Unsafe HTTP Methods
  F042: true  # LDAP Injection
  F052: true  # Weak Hash
  F063: true  # Unencrypted Channel
  F070: true  # Weak Credentials
  F079: true  # Host Header Injection
  F085: true  # XML External Entities
  F091: true  # Command Injection
  F096: true  # Insecure Service
  F097: true  # Insecure Connection
  F112: true  # Missing HTTP Security Headers
  F127: true  # Open Redirect
  F134: true  # Weak Secret Generation
  F143: true  # Unverified SSL
  F152: true  # Sensitive Data in URL
  F153: true  # Sensitive Data in GET
  F160: true  # Weak Cipher

# Paths to include (relative to working_dir)
include:
  - "website/"
  - "."

# Paths to exclude
exclude:
  - ".git/"
  - "node_modules/"
  - "vendor/"

# APK specific settings (not applicable but won't hurt)
apk:
  exclude: []
  include: []

# Additional settings
multifile: false
timeout: 300 