# Simple Skims Configuration for WackoPicko
namespace: "wackopicko-scan"
working_dir: "."

# Output settings - simple CSV format
output:
  format: "CSV"
  file_path: "vulnerabilities.csv"

# Focus on the most critical vulnerabilities for web apps
checks:
  F001: true  # SQL Injection
  F004: true  # Cross-Site Scripting (XSS)  
  F008: true  # Path Traversal
  F021: true  # Path Injection
  F034: true  # Unvalidated Redirect
  F091: true  # Command Injection
  F127: true  # Open Redirect

# Simple path configuration
include:
  - "website/"
  - "."

exclude:
  - ".git/"
  - "node_modules/" 