# Following Fluid Attacks guide: https://help.fluidattacks.com/portal/en/kb/articles/scan-with-a-configuration-file

namespace: wackopicko

output:
  file_path: ./Fluid-Attacks-Results.csv
  format: CSV

working_dir: .
language: EN
sast:
  include:
    - .
  exclude:
    - glob(**/node_modules/**)
    - glob(**/test/**)
    - glob(**/.git/**)
    - glob(**/vendor/**)
    - glob(**/logs/**)
    - glob(**/tmp/**)
    - glob(**/cache/**)
    - glob(**/dist/**)
    - glob(**/build/**)
    - glob(**/*.min.js)
    - glob(**/*.min.css) 